name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub or GitHub Container Registry
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/simplylove-discordleaderboard:${{ github.ref_name }} ./DiscordBot

    # Push the Docker image
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/simplylove-discordleaderboard:${{ github.ref_name }}

    # Push the Docker image with 'latest' tag
    - name: Push Docker image (latest)
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/simplylove-discordleaderboard:${{ github.ref_name }} \
                   ${{ secrets.DOCKER_USERNAME }}/simplylove-discordleaderboard:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/simplylove-discordleaderboard:latest
